package poolingpeople.persistance.neo4j.ingestor.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Changes generated by hbm2java
 */
@Entity
@Table(name = "changes", catalog = "redmine")
public class Changes implements java.io.Serializable {

	private Integer id;
	private int changesetId;
	private String action;
	private String path;
	private String fromPath;
	private String fromRevision;
	private String revision;
	private String branch;

	public Changes() {
	}

	public Changes(int changesetId, String action, String path) {
		this.changesetId = changesetId;
		this.action = action;
		this.path = path;
	}

	public Changes(int changesetId, String action, String path,
			String fromPath, String fromRevision, String revision, String branch) {
		this.changesetId = changesetId;
		this.action = action;
		this.path = path;
		this.fromPath = fromPath;
		this.fromRevision = fromRevision;
		this.revision = revision;
		this.branch = branch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "changeset_id", nullable = false)
	public int getChangesetId() {
		return this.changesetId;
	}

	public void setChangesetId(int changesetId) {
		this.changesetId = changesetId;
	}

	@Column(name = "action", nullable = false, length = 1)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "path", nullable = false, length = 65535)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "from_path", length = 65535)
	public String getFromPath() {
		return this.fromPath;
	}

	public void setFromPath(String fromPath) {
		this.fromPath = fromPath;
	}

	@Column(name = "from_revision")
	public String getFromRevision() {
		return this.fromRevision;
	}

	public void setFromRevision(String fromRevision) {
		this.fromRevision = fromRevision;
	}

	@Column(name = "revision")
	public String getRevision() {
		return this.revision;
	}

	public void setRevision(String revision) {
		this.revision = revision;
	}

	@Column(name = "branch")
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

}
