package poolingpeople.persistance.neo4j.ingestor.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CustomFieldsProjects generated by hbm2java
 */
@Entity
@Table(name = "custom_fields_projects", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"custom_field_id", "project_id" }))
public class CustomFieldsProjects implements java.io.Serializable {

	private CustomFieldsProjectsId id;

	public CustomFieldsProjects() {
	}

	public CustomFieldsProjects(CustomFieldsProjectsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customFieldId", column = @Column(name = "custom_field_id", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false)) })
	public CustomFieldsProjectsId getId() {
		return this.id;
	}

	public void setId(CustomFieldsProjectsId id) {
		this.id = id;
	}

}
