package poolingpeople.persistance.neo4j.ingestor.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "redmine")
public class Roles implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer position;
	private Boolean assignable;
	private int builtin;
	private String permissions;
	private String issuesVisibility;

	public Roles() {
	}

	public Roles(String name, int builtin, String issuesVisibility) {
		this.name = name;
		this.builtin = builtin;
		this.issuesVisibility = issuesVisibility;
	}

	public Roles(String name, Integer position, Boolean assignable,
			int builtin, String permissions, String issuesVisibility) {
		this.name = name;
		this.position = position;
		this.assignable = assignable;
		this.builtin = builtin;
		this.permissions = permissions;
		this.issuesVisibility = issuesVisibility;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "assignable")
	public Boolean getAssignable() {
		return this.assignable;
	}

	public void setAssignable(Boolean assignable) {
		this.assignable = assignable;
	}

	@Column(name = "builtin", nullable = false)
	public int getBuiltin() {
		return this.builtin;
	}

	public void setBuiltin(int builtin) {
		this.builtin = builtin;
	}

	@Column(name = "permissions", length = 65535)
	public String getPermissions() {
		return this.permissions;
	}

	public void setPermissions(String permissions) {
		this.permissions = permissions;
	}

	@Column(name = "issues_visibility", nullable = false, length = 30)
	public String getIssuesVisibility() {
		return this.issuesVisibility;
	}

	public void setIssuesVisibility(String issuesVisibility) {
		this.issuesVisibility = issuesVisibility;
	}

}
