package poolingpeople.persistance.neo4j.ingestor.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import poolingpeople.persistance.neo4j.ingestor.HasId;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "redmine")
public class Users implements java.io.Serializable, HasId{

	private Integer id;
	private String login;
	private String hashedPassword;
	private String firstname;
	private String lastname;
	private String mail;
	private boolean admin;
	private int status;
	private Date lastLoginOn;
	private String language;
	private Integer authSourceId;
	private Date createdOn;
	private Date updatedOn;
	private String type;
	private String identityUrl;
	private String mailNotification;
	private String salt;

	public Users() {
	}

	public Users(String login, String hashedPassword, String firstname,
			String lastname, String mail, boolean admin, int status,
			String mailNotification) {
		
		this.login = login;
		this.hashedPassword = hashedPassword;
		this.firstname = firstname;
		this.lastname = lastname;
		this.mail = mail;
		this.admin = admin;
		this.status = status;
		this.mailNotification = mailNotification;
	}

	public Users(String login, String hashedPassword, String firstname,
			String lastname, String mail, boolean admin, int status,
			Date lastLoginOn, String language, Integer authSourceId,
			Date createdOn, Date updatedOn, String type, String identityUrl,
			String mailNotification, String salt) {
		this.login = login;
		this.hashedPassword = hashedPassword;
		this.firstname = firstname;
		this.lastname = lastname;
		this.mail = mail;
		this.admin = admin;
		this.status = status;
		this.lastLoginOn = lastLoginOn;
		this.language = language;
		this.authSourceId = authSourceId;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.type = type;
		this.identityUrl = identityUrl;
		this.mailNotification = mailNotification;
		this.salt = salt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "hashed_password", nullable = false, length = 40)
	public String getHashedPassword() {
		return this.hashedPassword;
	}

	public void setHashedPassword(String hashedPassword) {
		this.hashedPassword = hashedPassword;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "mail", nullable = false, length = 60)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "admin", nullable = false)
	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_on", length = 19)
	public Date getLastLoginOn() {
		return this.lastLoginOn;
	}

	public void setLastLoginOn(Date lastLoginOn) {
		this.lastLoginOn = lastLoginOn;
	}

	@Column(name = "language", length = 5)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "auth_source_id")
	public Integer getAuthSourceId() {
		return this.authSourceId;
	}

	public void setAuthSourceId(Integer authSourceId) {
		this.authSourceId = authSourceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "identity_url")
	public String getIdentityUrl() {
		return this.identityUrl;
	}

	public void setIdentityUrl(String identityUrl) {
		this.identityUrl = identityUrl;
	}

	@Column(name = "mail_notification", nullable = false)
	public String getMailNotification() {
		return this.mailNotification;
	}

	public void setMailNotification(String mailNotification) {
		this.mailNotification = mailNotification;
	}

	@Column(name = "salt", length = 64)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

}
