package poolingpeople.persistance.neo4j.ingestor.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * WikiContentVersions generated by hbm2java
 */
@Entity
@Table(name = "wiki_content_versions", catalog = "redmine")
public class WikiContentVersions implements java.io.Serializable {

	private Integer id;
	private int version;
	private int wikiContentId;
	private int pageId;
	private Integer authorId;
	private byte[] data;
	private String compression;
	private String comments;
	private Date updatedOn;

	public WikiContentVersions() {
	}

	public WikiContentVersions(int wikiContentId, int pageId, Date updatedOn) {
		this.wikiContentId = wikiContentId;
		this.pageId = pageId;
		this.updatedOn = updatedOn;
	}

	public WikiContentVersions(int wikiContentId, int pageId, Integer authorId,
			byte[] data, String compression, String comments, Date updatedOn) {
		this.wikiContentId = wikiContentId;
		this.pageId = pageId;
		this.authorId = authorId;
		this.data = data;
		this.compression = compression;
		this.comments = comments;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "wiki_content_id", nullable = false)
	public int getWikiContentId() {
		return this.wikiContentId;
	}

	public void setWikiContentId(int wikiContentId) {
		this.wikiContentId = wikiContentId;
	}

	@Column(name = "page_id", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Column(name = "author_id")
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "data")
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Column(name = "compression", length = 6)
	public String getCompression() {
		return this.compression;
	}

	public void setCompression(String compression) {
		this.compression = compression;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", nullable = false, length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
