package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IssueStatuses generated by hbm2java
 */
@Entity
@Table(name = "issue_statuses", catalog = "redmine")
public class IssueStatuses implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean isClosed;
	private boolean isDefault;
	private Integer position;
	private Integer defaultDoneRatio;

	public IssueStatuses() {
	}

	public IssueStatuses(String name, boolean isClosed, boolean isDefault) {
		this.name = name;
		this.isClosed = isClosed;
		this.isDefault = isDefault;
	}

	public IssueStatuses(String name, boolean isClosed, boolean isDefault,
			Integer position, Integer defaultDoneRatio) {
		this.name = name;
		this.isClosed = isClosed;
		this.isDefault = isDefault;
		this.position = position;
		this.defaultDoneRatio = defaultDoneRatio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_closed", nullable = false)
	public boolean isIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(boolean isClosed) {
		this.isClosed = isClosed;
	}

	@Column(name = "is_default", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "default_done_ratio")
	public Integer getDefaultDoneRatio() {
		return this.defaultDoneRatio;
	}

	public void setDefaultDoneRatio(Integer defaultDoneRatio) {
		this.defaultDoneRatio = defaultDoneRatio;
	}

}
