package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * OpenIdAuthenticationNonces generated by hbm2java
 */
@Entity
@Table(name = "open_id_authentication_nonces", catalog = "redmine")
public class OpenIdAuthenticationNonces implements java.io.Serializable {

	private Integer id;
	private int timestamp;
	private String serverUrl;
	private String salt;

	public OpenIdAuthenticationNonces() {
	}

	public OpenIdAuthenticationNonces(String salt) {
		this.salt = salt;
	}

	public OpenIdAuthenticationNonces(String serverUrl, String salt) {
		this.serverUrl = serverUrl;
		this.salt = salt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "timestamp", nullable = false)
	public int getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "server_url")
	public String getServerUrl() {
		return this.serverUrl;
	}

	public void setServerUrl(String serverUrl) {
		this.serverUrl = serverUrl;
	}

	@Column(name = "salt", nullable = false)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

}
