package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import poolingpeople.exporter.HasId;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects", catalog = "redmine")
public class Projects implements java.io.Serializable, HasId {

	private Integer id;
	private String name;
	private String description;
	private String homepage;
	private boolean isPublic;
	private Integer parentId;
	private Date createdOn;
	private Date updatedOn;
	private String identifier;
	private int status;
	private Integer lft;
	private Integer rgt;
	private boolean inheritMembers;

	public Projects() {
	}

	public Projects(String name, boolean isPublic, int status,
			boolean inheritMembers) {
		this.name = name;
		this.isPublic = isPublic;
		this.status = status;
		this.inheritMembers = inheritMembers;
	}

	public Projects(String name, String description, String homepage,
			boolean isPublic, Integer parentId, Date createdOn, Date updatedOn,
			String identifier, int status, Integer lft, Integer rgt,
			boolean inheritMembers) {
		this.name = name;
		this.description = description;
		this.homepage = homepage;
		this.isPublic = isPublic;
		this.parentId = parentId;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.identifier = identifier;
		this.status = status;
		this.lft = lft;
		this.rgt = rgt;
		this.inheritMembers = inheritMembers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "homepage")
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@Column(name = "is_public", nullable = false)
	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "identifier")
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "lft")
	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	@Column(name = "rgt")
	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	@Column(name = "inherit_members", nullable = false)
	public boolean isInheritMembers() {
		return this.inheritMembers;
	}

	public void setInheritMembers(boolean inheritMembers) {
		this.inheritMembers = inheritMembers;
	}

}
