package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleClosedEntries generated by hbm2java
 */
@Entity
@Table(name = "schedule_closed_entries", catalog = "redmine")
public class ScheduleClosedEntries implements java.io.Serializable {

	private Integer id;
	private int userId;
	private Date date;
	private float hours;
	private String comment;

	public ScheduleClosedEntries() {
	}

	public ScheduleClosedEntries(int userId, Date date, float hours) {
		this.userId = userId;
		this.date = date;
		this.hours = hours;
	}

	public ScheduleClosedEntries(int userId, Date date, float hours,
			String comment) {
		this.userId = userId;
		this.date = date;
		this.hours = hours;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "hours", nullable = false, precision = 12, scale = 0)
	public float getHours() {
		return this.hours;
	}

	public void setHours(float hours) {
		this.hours = hours;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
