package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Repositories generated by hbm2java
 */
@Entity
@Table(name = "repositories", catalog = "redmine")
public class Repositories implements java.io.Serializable {

	private Integer id;
	private int projectId;
	private String url;
	private String login;
	private String password;
	private String rootUrl;
	private String type;
	private String pathEncoding;
	private String logEncoding;
	private String extraInfo;
	private String identifier;
	private Boolean isDefault;

	public Repositories() {
	}

	public Repositories(int projectId, String url) {
		this.projectId = projectId;
		this.url = url;
	}

	public Repositories(int projectId, String url, String login,
			String password, String rootUrl, String type, String pathEncoding,
			String logEncoding, String extraInfo, String identifier,
			Boolean isDefault) {
		this.projectId = projectId;
		this.url = url;
		this.login = login;
		this.password = password;
		this.rootUrl = rootUrl;
		this.type = type;
		this.pathEncoding = pathEncoding;
		this.logEncoding = logEncoding;
		this.extraInfo = extraInfo;
		this.identifier = identifier;
		this.isDefault = isDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "login", length = 60)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "root_url")
	public String getRootUrl() {
		return this.rootUrl;
	}

	public void setRootUrl(String rootUrl) {
		this.rootUrl = rootUrl;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "path_encoding", length = 64)
	public String getPathEncoding() {
		return this.pathEncoding;
	}

	public void setPathEncoding(String pathEncoding) {
		this.pathEncoding = pathEncoding;
	}

	@Column(name = "log_encoding", length = 64)
	public String getLogEncoding() {
		return this.logEncoding;
	}

	public void setLogEncoding(String logEncoding) {
		this.logEncoding = logEncoding;
	}

	@Column(name = "extra_info", length = 65535)
	public String getExtraInfo() {
		return this.extraInfo;
	}

	public void setExtraInfo(String extraInfo) {
		this.extraInfo = extraInfo;
	}

	@Column(name = "identifier")
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Column(name = "is_default")
	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

}
