package poolingpeople.exporter.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPreferences generated by hbm2java
 */
@Entity
@Table(name = "user_preferences", catalog = "redmine")
public class UserPreferences implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String others;
	private Boolean hideMail;
	private String timeZone;

	public UserPreferences() {
	}

	public UserPreferences(int userId) {
		this.userId = userId;
	}

	public UserPreferences(int userId, String others, Boolean hideMail,
			String timeZone) {
		this.userId = userId;
		this.others = others;
		this.hideMail = hideMail;
		this.timeZone = timeZone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "others", length = 65535)
	public String getOthers() {
		return this.others;
	}

	public void setOthers(String others) {
		this.others = others;
	}

	@Column(name = "hide_mail")
	public Boolean getHideMail() {
		return this.hideMail;
	}

	public void setHideMail(Boolean hideMail) {
		this.hideMail = hideMail;
	}

	@Column(name = "time_zone")
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

}
