package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "redmine")
public class Comments implements java.io.Serializable {

	private Integer id;
	private String commentedType;
	private int commentedId;
	private int authorId;
	private String comments;
	private Date createdOn;
	private Date updatedOn;

	public Comments() {
	}

	public Comments(String commentedType, int commentedId, int authorId,
			Date createdOn, Date updatedOn) {
		this.commentedType = commentedType;
		this.commentedId = commentedId;
		this.authorId = authorId;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	public Comments(String commentedType, int commentedId, int authorId,
			String comments, Date createdOn, Date updatedOn) {
		this.commentedType = commentedType;
		this.commentedId = commentedId;
		this.authorId = authorId;
		this.comments = comments;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "commented_type", nullable = false, length = 30)
	public String getCommentedType() {
		return this.commentedType;
	}

	public void setCommentedType(String commentedType) {
		this.commentedType = commentedType;
	}

	@Column(name = "commented_id", nullable = false)
	public int getCommentedId() {
		return this.commentedId;
	}

	public void setCommentedId(int commentedId) {
		this.commentedId = commentedId;
	}

	@Column(name = "author_id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", nullable = false, length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
