package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CustomFieldsTrackers generated by hbm2java
 */
@Entity
@Table(name = "custom_fields_trackers", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"custom_field_id", "tracker_id" }))
public class CustomFieldsTrackers implements java.io.Serializable {

	private CustomFieldsTrackersId id;

	public CustomFieldsTrackers() {
	}

	public CustomFieldsTrackers(CustomFieldsTrackersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customFieldId", column = @Column(name = "custom_field_id", nullable = false)),
			@AttributeOverride(name = "trackerId", column = @Column(name = "tracker_id", nullable = false)) })
	public CustomFieldsTrackersId getId() {
		return this.id;
	}

	public void setId(CustomFieldsTrackersId id) {
		this.id = id;
	}

}
