package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deliverables generated by hbm2java
 */
@Entity
@Table(name = "deliverables", catalog = "redmine")
public class Deliverables implements java.io.Serializable {

	private Integer id;
	private String subject;
	private String description;
	private String type;
	private Boolean projectManagerSignoff;
	private Boolean clientSignoff;
	private Integer projectId;
	private BigDecimal budget;
	private BigDecimal overhead;
	private BigDecimal materials;
	private BigDecimal profit;
	private BigDecimal costPerHour;
	private BigDecimal totalHours;
	private BigDecimal fixedCost;
	private Integer overheadPercent;
	private Integer materialsPercent;
	private Integer profitPercent;
	private Date due;

	public Deliverables() {
	}

	public Deliverables(String subject, String description, String type,
			Boolean projectManagerSignoff, Boolean clientSignoff,
			Integer projectId, BigDecimal budget, BigDecimal overhead,
			BigDecimal materials, BigDecimal profit, BigDecimal costPerHour,
			BigDecimal totalHours, BigDecimal fixedCost,
			Integer overheadPercent, Integer materialsPercent,
			Integer profitPercent, Date due) {
		this.subject = subject;
		this.description = description;
		this.type = type;
		this.projectManagerSignoff = projectManagerSignoff;
		this.clientSignoff = clientSignoff;
		this.projectId = projectId;
		this.budget = budget;
		this.overhead = overhead;
		this.materials = materials;
		this.profit = profit;
		this.costPerHour = costPerHour;
		this.totalHours = totalHours;
		this.fixedCost = fixedCost;
		this.overheadPercent = overheadPercent;
		this.materialsPercent = materialsPercent;
		this.profitPercent = profitPercent;
		this.due = due;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "project_manager_signoff")
	public Boolean getProjectManagerSignoff() {
		return this.projectManagerSignoff;
	}

	public void setProjectManagerSignoff(Boolean projectManagerSignoff) {
		this.projectManagerSignoff = projectManagerSignoff;
	}

	@Column(name = "client_signoff")
	public Boolean getClientSignoff() {
		return this.clientSignoff;
	}

	public void setClientSignoff(Boolean clientSignoff) {
		this.clientSignoff = clientSignoff;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "budget", precision = 15)
	public BigDecimal getBudget() {
		return this.budget;
	}

	public void setBudget(BigDecimal budget) {
		this.budget = budget;
	}

	@Column(name = "overhead", precision = 15)
	public BigDecimal getOverhead() {
		return this.overhead;
	}

	public void setOverhead(BigDecimal overhead) {
		this.overhead = overhead;
	}

	@Column(name = "materials", precision = 15)
	public BigDecimal getMaterials() {
		return this.materials;
	}

	public void setMaterials(BigDecimal materials) {
		this.materials = materials;
	}

	@Column(name = "profit", precision = 15)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "cost_per_hour", precision = 15)
	public BigDecimal getCostPerHour() {
		return this.costPerHour;
	}

	public void setCostPerHour(BigDecimal costPerHour) {
		this.costPerHour = costPerHour;
	}

	@Column(name = "total_hours", precision = 15)
	public BigDecimal getTotalHours() {
		return this.totalHours;
	}

	public void setTotalHours(BigDecimal totalHours) {
		this.totalHours = totalHours;
	}

	@Column(name = "fixed_cost", precision = 15)
	public BigDecimal getFixedCost() {
		return this.fixedCost;
	}

	public void setFixedCost(BigDecimal fixedCost) {
		this.fixedCost = fixedCost;
	}

	@Column(name = "overhead_percent")
	public Integer getOverheadPercent() {
		return this.overheadPercent;
	}

	public void setOverheadPercent(Integer overheadPercent) {
		this.overheadPercent = overheadPercent;
	}

	@Column(name = "materials_percent")
	public Integer getMaterialsPercent() {
		return this.materialsPercent;
	}

	public void setMaterialsPercent(Integer materialsPercent) {
		this.materialsPercent = materialsPercent;
	}

	@Column(name = "profit_percent")
	public Integer getProfitPercent() {
		return this.profitPercent;
	}

	public void setProfitPercent(Integer profitPercent) {
		this.profitPercent = profitPercent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due", length = 10)
	public Date getDue() {
		return this.due;
	}

	public void setDue(Date due) {
		this.due = due;
	}

}
