package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Journals generated by hbm2java
 */
@Entity
@Table(name = "journals", catalog = "redmine")
public class Journals implements java.io.Serializable {

	private Integer id;
	private int journalizedId;
	private String journalizedType;
	private int userId;
	private String notes;
	private Date createdOn;
	private boolean privateNotes;

	public Journals() {
	}

	public Journals(int journalizedId, String journalizedType, int userId,
			Date createdOn, boolean privateNotes) {
		this.journalizedId = journalizedId;
		this.journalizedType = journalizedType;
		this.userId = userId;
		this.createdOn = createdOn;
		this.privateNotes = privateNotes;
	}

	public Journals(int journalizedId, String journalizedType, int userId,
			String notes, Date createdOn, boolean privateNotes) {
		this.journalizedId = journalizedId;
		this.journalizedType = journalizedType;
		this.userId = userId;
		this.notes = notes;
		this.createdOn = createdOn;
		this.privateNotes = privateNotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "journalized_id", nullable = false)
	public int getJournalizedId() {
		return this.journalizedId;
	}

	public void setJournalizedId(int journalizedId) {
		this.journalizedId = journalizedId;
	}

	@Column(name = "journalized_type", nullable = false, length = 30)
	public String getJournalizedType() {
		return this.journalizedType;
	}

	public void setJournalizedType(String journalizedType) {
		this.journalizedType = journalizedType;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "private_notes", nullable = false)
	public boolean isPrivateNotes() {
		return this.privateNotes;
	}

	public void setPrivateNotes(boolean privateNotes) {
		this.privateNotes = privateNotes;
	}

}
