package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProjectsTrackers generated by hbm2java
 */
@Entity
@Table(name = "projects_trackers", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"project_id", "tracker_id" }))
public class ProjectsTrackers implements java.io.Serializable {

	private ProjectsTrackersId id;

	public ProjectsTrackers() {
	}

	public ProjectsTrackers(ProjectsTrackersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false)),
			@AttributeOverride(name = "trackerId", column = @Column(name = "tracker_id", nullable = false)) })
	public ProjectsTrackersId getId() {
		return this.id;
	}

	public void setId(ProjectsTrackersId id) {
		this.id = id;
	}

}
