package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectsTrackersId generated by hbm2java
 */
@Embeddable
public class ProjectsTrackersId implements java.io.Serializable {

	private int projectId;
	private int trackerId;

	public ProjectsTrackersId() {
	}

	public ProjectsTrackersId(int projectId, int trackerId) {
		this.projectId = projectId;
		this.trackerId = trackerId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "tracker_id", nullable = false)
	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectsTrackersId))
			return false;
		ProjectsTrackersId castOther = (ProjectsTrackersId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& (this.getTrackerId() == castOther.getTrackerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getTrackerId();
		return result;
	}

}
