package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ScheduleDefaults generated by hbm2java
 */
@Entity
@Table(name = "schedule_defaults", catalog = "redmine")
public class ScheduleDefaults implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String weekdayHours;

	public ScheduleDefaults() {
	}

	public ScheduleDefaults(int userId) {
		this.userId = userId;
	}

	public ScheduleDefaults(int userId, String weekdayHours) {
		this.userId = userId;
		this.weekdayHours = weekdayHours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "weekday_hours", length = 65535)
	public String getWeekdayHours() {
		return this.weekdayHours;
	}

	public void setWeekdayHours(String weekdayHours) {
		this.weekdayHours = weekdayHours;
	}

}
