package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SchemaMigrations generated by hbm2java
 */
@Entity
@Table(name = "schema_migrations", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = "version"))
public class SchemaMigrations implements java.io.Serializable {

	private String version;

	public SchemaMigrations() {
	}

	public SchemaMigrations(String version) {
		this.version = version;
	}

	@Id
	@Column(name = "version", unique = true, nullable = false)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

}
