package poolingpeople.persistance.neo4j.ingestor;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflows generated by hbm2java
 */
@Entity
@Table(name = "workflows", catalog = "redmine")
public class Workflows implements java.io.Serializable {

	private Integer id;
	private int trackerId;
	private int oldStatusId;
	private int newStatusId;
	private int roleId;
	private boolean assignee;
	private boolean author;
	private String type;
	private String fieldName;
	private String rule;

	public Workflows() {
	}

	public Workflows(int trackerId, int oldStatusId, int newStatusId,
			int roleId, boolean assignee, boolean author) {
		this.trackerId = trackerId;
		this.oldStatusId = oldStatusId;
		this.newStatusId = newStatusId;
		this.roleId = roleId;
		this.assignee = assignee;
		this.author = author;
	}

	public Workflows(int trackerId, int oldStatusId, int newStatusId,
			int roleId, boolean assignee, boolean author, String type,
			String fieldName, String rule) {
		this.trackerId = trackerId;
		this.oldStatusId = oldStatusId;
		this.newStatusId = newStatusId;
		this.roleId = roleId;
		this.assignee = assignee;
		this.author = author;
		this.type = type;
		this.fieldName = fieldName;
		this.rule = rule;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tracker_id", nullable = false)
	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	@Column(name = "old_status_id", nullable = false)
	public int getOldStatusId() {
		return this.oldStatusId;
	}

	public void setOldStatusId(int oldStatusId) {
		this.oldStatusId = oldStatusId;
	}

	@Column(name = "new_status_id", nullable = false)
	public int getNewStatusId() {
		return this.newStatusId;
	}

	public void setNewStatusId(int newStatusId) {
		this.newStatusId = newStatusId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "assignee", nullable = false)
	public boolean isAssignee() {
		return this.assignee;
	}

	public void setAssignee(boolean assignee) {
		this.assignee = assignee;
	}

	@Column(name = "author", nullable = false)
	public boolean isAuthor() {
		return this.author;
	}

	public void setAuthor(boolean author) {
		this.author = author;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "field_name", length = 30)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "rule", length = 30)
	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

}
