package poolingpeople.webapplication.business.neo4j;

public enum NodePropertyName {
	TYPE, ID, START, END, ACTIVE, TITLE, DESCRIPTION, 
	PRIORITY, STATUS, START_DATE, STARTDATE, PROGRESS, END_DATE, DURATION, EMAIL, LASTNAME, PASSWORD, FIRSTNAME, DATE, COMMENT, TIME, EFFORT, BIRTHDATE

}
