package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChangesetParents generated by hbm2java
 */
@Entity
@Table(name = "changeset_parents", catalog = "redmine")
public class ChangesetParents implements java.io.Serializable {

	private ChangesetParentsId id;

	public ChangesetParents() {
	}

	public ChangesetParents(ChangesetParentsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "changesetId", column = @Column(name = "changeset_id", nullable = false)),
			@AttributeOverride(name = "parentId", column = @Column(name = "parent_id", nullable = false)) })
	public ChangesetParentsId getId() {
		return this.id;
	}

	public void setId(ChangesetParentsId id) {
		this.id = id;
	}

}
