package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Changesets generated by hbm2java
 */
@Entity
@Table(name = "changesets", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"repository_id", "revision" }))
public class Changesets implements java.io.Serializable {

	private Integer id;
	private int repositoryId;
	private String revision;
	private String committer;
	private Date committedOn;
	private String comments;
	private Date commitDate;
	private String scmid;
	private Integer userId;

	public Changesets() {
	}

	public Changesets(int repositoryId, String revision, Date committedOn) {
		this.repositoryId = repositoryId;
		this.revision = revision;
		this.committedOn = committedOn;
	}

	public Changesets(int repositoryId, String revision, String committer,
			Date committedOn, String comments, Date commitDate, String scmid,
			Integer userId) {
		this.repositoryId = repositoryId;
		this.revision = revision;
		this.committer = committer;
		this.committedOn = committedOn;
		this.comments = comments;
		this.commitDate = commitDate;
		this.scmid = scmid;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "repository_id", nullable = false)
	public int getRepositoryId() {
		return this.repositoryId;
	}

	public void setRepositoryId(int repositoryId) {
		this.repositoryId = repositoryId;
	}

	@Column(name = "revision", nullable = false)
	public String getRevision() {
		return this.revision;
	}

	public void setRevision(String revision) {
		this.revision = revision;
	}

	@Column(name = "committer")
	public String getCommitter() {
		return this.committer;
	}

	public void setCommitter(String committer) {
		this.committer = committer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "committed_on", nullable = false, length = 19)
	public Date getCommittedOn() {
		return this.committedOn;
	}

	public void setCommittedOn(Date committedOn) {
		this.committedOn = committedOn;
	}

	@Column(name = "comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "commit_date", length = 10)
	public Date getCommitDate() {
		return this.commitDate;
	}

	public void setCommitDate(Date commitDate) {
		this.commitDate = commitDate;
	}

	@Column(name = "scmid")
	public String getScmid() {
		return this.scmid;
	}

	public void setScmid(String scmid) {
		this.scmid = scmid;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
