package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomFieldsProjectsId generated by hbm2java
 */
@Embeddable
public class CustomFieldsProjectsId implements java.io.Serializable {

	private int customFieldId;
	private int projectId;

	public CustomFieldsProjectsId() {
	}

	public CustomFieldsProjectsId(int customFieldId, int projectId) {
		this.customFieldId = customFieldId;
		this.projectId = projectId;
	}

	@Column(name = "custom_field_id", nullable = false)
	public int getCustomFieldId() {
		return this.customFieldId;
	}

	public void setCustomFieldId(int customFieldId) {
		this.customFieldId = customFieldId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomFieldsProjectsId))
			return false;
		CustomFieldsProjectsId castOther = (CustomFieldsProjectsId) other;

		return (this.getCustomFieldId() == castOther.getCustomFieldId())
				&& (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomFieldId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
