package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupsUsers generated by hbm2java
 */
@Entity
@Table(name = "groups_users", catalog = "redmine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"group_id", "user_id" }))
public class GroupsUsers implements java.io.Serializable {

	private GroupsUsersId id;

	public GroupsUsers() {
	}

	public GroupsUsers(GroupsUsersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public GroupsUsersId getId() {
		return this.id;
	}

	public void setId(GroupsUsersId id) {
		this.id = id;
	}

}
