package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import poolingpeople.exporter.HasId;

/**
 * Issues generated by hbm2java
 */
@Entity
@Table(name = "issues", catalog = "redmine")
public class Issues implements java.io.Serializable, HasId {

	private Integer id;
	private int trackerId;
	private int projectId;
	private String subject;
	private String description;
	private Date dueDate;
	private Integer categoryId;
	private int statusId;
	private Integer assignedToId;
	private int priorityId;
	private Integer fixedVersionId;
	private int authorId;
	private int lockVersion;
	private Date createdOn;
	private Date updatedOn;
	private Date startDate;
	private int doneRatio;
	private Float estimatedHours;
	private Integer deliverableId;
	private Integer parentId;
	private Integer rootId;
	private Integer lft;
	private Integer rgt;
	private boolean isPrivate;
	private Date closedOn;

	public Issues() {
	}

	public Issues(int trackerId, int projectId, String subject, int statusId,
			int priorityId, int authorId, int lockVersion, int doneRatio,
			boolean isPrivate) {
		this.trackerId = trackerId;
		this.projectId = projectId;
		this.subject = subject;
		this.statusId = statusId;
		this.priorityId = priorityId;
		this.authorId = authorId;
		this.lockVersion = lockVersion;
		this.doneRatio = doneRatio;
		this.isPrivate = isPrivate;
	}

	public Issues(int trackerId, int projectId, String subject,
			String description, Date dueDate, Integer categoryId, int statusId,
			Integer assignedToId, int priorityId, Integer fixedVersionId,
			int authorId, int lockVersion, Date createdOn, Date updatedOn,
			Date startDate, int doneRatio, Float estimatedHours,
			Integer deliverableId, Integer parentId, Integer rootId,
			Integer lft, Integer rgt, boolean isPrivate, Date closedOn) {
		this.trackerId = trackerId;
		this.projectId = projectId;
		this.subject = subject;
		this.description = description;
		this.dueDate = dueDate;
		this.categoryId = categoryId;
		this.statusId = statusId;
		this.assignedToId = assignedToId;
		this.priorityId = priorityId;
		this.fixedVersionId = fixedVersionId;
		this.authorId = authorId;
		this.lockVersion = lockVersion;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.startDate = startDate;
		this.doneRatio = doneRatio;
		this.estimatedHours = estimatedHours;
		this.deliverableId = deliverableId;
		this.parentId = parentId;
		this.rootId = rootId;
		this.lft = lft;
		this.rgt = rgt;
		this.isPrivate = isPrivate;
		this.closedOn = closedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tracker_id", nullable = false)
	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "assigned_to_id")
	public Integer getAssignedToId() {
		return this.assignedToId;
	}

	public void setAssignedToId(Integer assignedToId) {
		this.assignedToId = assignedToId;
	}

	@Column(name = "priority_id", nullable = false)
	public int getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(int priorityId) {
		this.priorityId = priorityId;
	}

	@Column(name = "fixed_version_id")
	public Integer getFixedVersionId() {
		return this.fixedVersionId;
	}

	public void setFixedVersionId(Integer fixedVersionId) {
		this.fixedVersionId = fixedVersionId;
	}

	@Column(name = "author_id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "lock_version", nullable = false)
	public int getLockVersion() {
		return this.lockVersion;
	}

	public void setLockVersion(int lockVersion) {
		this.lockVersion = lockVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "done_ratio", nullable = false)
	public int getDoneRatio() {
		return this.doneRatio;
	}

	public void setDoneRatio(int doneRatio) {
		this.doneRatio = doneRatio;
	}

	@Column(name = "estimated_hours", precision = 12, scale = 0)
	public Float getEstimatedHours() {
		return this.estimatedHours;
	}

	public void setEstimatedHours(Float estimatedHours) {
		this.estimatedHours = estimatedHours;
	}

	@Column(name = "deliverable_id")
	public Integer getDeliverableId() {
		return this.deliverableId;
	}

	public void setDeliverableId(Integer deliverableId) {
		this.deliverableId = deliverableId;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "root_id")
	public Integer getRootId() {
		return this.rootId;
	}

	public void setRootId(Integer rootId) {
		this.rootId = rootId;
	}

	@Column(name = "lft")
	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	@Column(name = "rgt")
	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	@Column(name = "is_private", nullable = false)
	public boolean isIsPrivate() {
		return this.isPrivate;
	}

	public void setIsPrivate(boolean isPrivate) {
		this.isPrivate = isPrivate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "closed_on", length = 19)
	public Date getClosedOn() {
		return this.closedOn;
	}

	public void setClosedOn(Date closedOn) {
		this.closedOn = closedOn;
	}

}
