package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpenIdAuthenticationAssociations generated by hbm2java
 */
@Entity
@Table(name = "open_id_authentication_associations", catalog = "redmine")
public class OpenIdAuthenticationAssociations implements java.io.Serializable {

	private Integer id;
	private Integer issued;
	private Integer lifetime;
	private String handle;
	private String assocType;
	private byte[] serverUrl;
	private byte[] secret;

	public OpenIdAuthenticationAssociations() {
	}

	public OpenIdAuthenticationAssociations(Integer issued, Integer lifetime,
			String handle, String assocType, byte[] serverUrl, byte[] secret) {
		this.issued = issued;
		this.lifetime = lifetime;
		this.handle = handle;
		this.assocType = assocType;
		this.serverUrl = serverUrl;
		this.secret = secret;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "issued")
	public Integer getIssued() {
		return this.issued;
	}

	public void setIssued(Integer issued) {
		this.issued = issued;
	}

	@Column(name = "lifetime")
	public Integer getLifetime() {
		return this.lifetime;
	}

	public void setLifetime(Integer lifetime) {
		this.lifetime = lifetime;
	}

	@Column(name = "handle")
	public String getHandle() {
		return this.handle;
	}

	public void setHandle(String handle) {
		this.handle = handle;
	}

	@Column(name = "assoc_type")
	public String getAssocType() {
		return this.assocType;
	}

	public void setAssocType(String assocType) {
		this.assocType = assocType;
	}

	@Column(name = "server_url")
	public byte[] getServerUrl() {
		return this.serverUrl;
	}

	public void setServerUrl(byte[] serverUrl) {
		this.serverUrl = serverUrl;
	}

	@Column(name = "secret")
	public byte[] getSecret() {
		return this.secret;
	}

	public void setSecret(byte[] secret) {
		this.secret = secret;
	}

}
