package poolingpeople.exporter.models.redmine;

// Generated Feb 17, 2014 1:20:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Wikis generated by hbm2java
 */
@Entity
@Table(name = "wikis", catalog = "redmine")
public class Wikis implements java.io.Serializable {

	private Integer id;
	private int projectId;
	private String startPage;
	private int status;

	public Wikis() {
	}

	public Wikis(int projectId, String startPage, int status) {
		this.projectId = projectId;
		this.startPage = startPage;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "start_page", nullable = false)
	public String getStartPage() {
		return this.startPage;
	}

	public void setStartPage(String startPage) {
		this.startPage = startPage;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
